<a href="https://colab.research.google.com/github/HILALOZTEMEL/BernoulliRBM-Chi_Scores-AutoEncoder-with--CICIDS2017-dataset/blob/main/BernoulliRBM_Chi_Scores_AutoEncoder_with_CICIDS2017_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.neural_network import BernoulliRBM
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

from sklearn.pipeline import Pipeline
from sklearn import linear_model


#kimlik doğrulama işlemi :drive in içinde çalışma ortamı sağlarız serverlarda
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive

df = pd.read_csv("/gdrive/My Drive/İstanbul Gedik Üniversitesi/DataMining/CICIDS2017.csv")
print('Dimensions of the Test set:',df.shape)

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).
/gdrive
Dimensions of the Test set: (1042557, 79)


In [ ]:
df.head()

Destination Port   Flow Duration   Total Fwd Packets  \
0              54865               3                   2   
1              55054             109                   1   
2              55055              52                   1   
3              46236              34                   1   
4              54863               3                   2   

    Total Backward Packets  Total Length of Fwd Packets  \
0                        0                           12   
1                        1                            6   
2                        1                            6   
3                        1                            6   
4                        0                           12   

    Total Length of Bwd Packets   Fwd Packet Length Max  \
0                             0                       6   
1                             6                       6   
2                             6                       6   
3                             6                       6   
4                             0                       6   

    Fwd Packet Length Min   Fwd Packet Length Mean   Fwd Packet Length Std  \
0                       6                      6.0                     0.0   
1                       6                      6.0                     0.0   
2                       6                      6.0                     0.0   
3                       6                      6.0                     0.0   
4                       6                      6.0                     0.0   

   ...   min_seg_size_forward  Active Mean   Active Std   Active Max  \
0  ...                     20          0.0          0.0            0   
1  ...                     20          0.0          0.0            0   
2  ...                     20          0.0          0.0            0   
3  ...                     20          0.0          0.0            0   
4  ...                     20          0.0          0.0            0   

    Active Min  Idle Mean   Idle Std   Idle Max   Idle Min   Label  
0            0        0.0        0.0          0          0  BENIGN  
1            0        0.0        0.0          0          0  BENIGN  
2            0        0.0        0.0          0          0  BENIGN  
3            0        0.0        0.0          0          0  BENIGN  
4            0        0.0        0.0          0          0  BENIGN  

[5 rows x 79 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing
labelencoder = LabelEncoder()
df.iloc[:, -1] = labelencoder.fit_transform(df.iloc[:, -1])
X = df.drop([' Label'],axis=1)
y=df[[' Label']]
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size = 0.7, test_size = 0.3, random_state = 0, stratify = y)
X_train = np.array(X_train)
for column in  X_train:
        median = np.nanmedian(column)
        column[np.isnan(column)] = median
        column[column == np.inf] = 0
        column[column == -np.inf] = 0

y_train = np.array(y_train)
for column in  y_train:
        median = np.nanmedian(column)
        column[np.isnan(column)] = median
        column[column == np.inf] = 0
        column[column == -np.inf] = 0

X_test = np.array(X_test)
for column in  X_test:
        median = np.nanmedian(column)
        column[np.isnan(column)] = median
        column[column == np.inf] = 0
        column[column == -np.inf] = 0

y_test = np.array(y_test)
for column in  y_test: 
        median = np.nanmedian(column)
        column[np.isnan(column)] = median
        column[column == np.inf] = 0
        column[column == -np.inf] = 0


In [ ]:
X_train.shape,X_test.shape , y_train.shape ,y_test.shape

((729789, 78), (312768, 78), (729789, 1), (312768, 1))

In [ ]:
rbm = BernoulliRBM(n_components=40, learning_rate=0.06, n_iter=100, verbose=1, random_state=101)
rbm.fit(X_train, y_train)

[BernoulliRBM] Iteration 1, pseudo-likelihood = -166189308315724.66, time = 14.73s
[BernoulliRBM] Iteration 2, pseudo-likelihood = -332606868003916.88, time = 17.20s
[BernoulliRBM] Iteration 3, pseudo-likelihood = -499024427634408.62, time = 16.03s
[BernoulliRBM] Iteration 4, pseudo-likelihood = -665441987431984.62, time = 16.88s
[BernoulliRBM] Iteration 5, pseudo-likelihood = -831859546987968.88, time = 17.21s
[BernoulliRBM] Iteration 6, pseudo-likelihood = -998277106706032.12, time = 15.85s
[BernoulliRBM] Iteration 7, pseudo-likelihood = -1164694666419538.75, time = 17.61s
[BernoulliRBM] Iteration 8, pseudo-likelihood = -1331112226175271.25, time = 14.89s
[BernoulliRBM] Iteration 9, pseudo-likelihood = -1497529785593212.50, time = 18.79s
[BernoulliRBM] Iteration 10, pseudo-likelihood = -1663947345264630.50, time = 14.24s
[BernoulliRBM] Iteration 11, pseudo-likelihood = -1830364905398344.25, time = 18.50s
[BernoulliRBM] Iteration 12, pseudo-likelihood = -1996782464540310.75, time = 14

BernoulliRBM(learning_rate=0.06, n_components=40, n_iter=100, random_state=101,
             verbose=1)

In [ ]:
X_train.shape,X_test.shape , y_train.shape ,y_test.shape

((729789, 78), (312768, 78), (729789, 1), (312768, 1))

In [ ]:
from sklearn.preprocessing import MinMaxScaler #fixed import

scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)


In [ ]:
from sklearn.feature_selection import chi2

chi_scores = chi2(X_train,y_train)
chi_scores

(array([3.63691115e+04, 1.44708123e+05, 4.04319145e+00, 4.35612479e+00,
        1.30380144e+02, 2.14221710e+00, 2.24937506e+03, 3.39767187e+03,
        3.81470417e+03, 2.97471606e+03, 9.19654379e+04, 9.53320038e+03,
        1.37528585e+05, 1.24065927e+05, 1.55949023e+00, 4.20629113e+01,
        1.63604181e+04, 8.01428980e+04, 2.07782602e+05, 2.07073344e+03,
        1.47596571e+05, 3.28230729e+04, 1.31307893e+05, 2.10860961e+05,
        1.47546123e+03, 2.91919184e+04, 7.62232142e+03, 3.67521229e+04,
        5.17838273e+04, 1.12139319e+03, 1.40015280e+04,            nan,
                   nan,            nan, 3.71220890e+00, 4.50492631e+00,
        2.99959613e+03, 4.76215017e+03, 3.49871301e+03, 6.06861475e+04,
        8.62223742e+04, 1.03426550e+05, 6.47681331e+04, 1.53156839e+05,
        1.40015280e+04, 1.33429728e+02, 1.15180786e+05, 4.83905676e+04,
        3.82726821e+04,            nan, 1.33429728e+02, 1.84001636e+02,
        8.07732960e+04, 3.81470417e+03, 1.37528585e+05, 3.712208

In [ ]:
X_train.shape,X_test.shape , y_train.shape ,y_test.shape

((729789, 78), (312768, 78), (729789, 1), (312768, 1))

In [ ]:
#Importing the Libraries
from sklearn.datasets import make_classification
from sklearn.datasets import make_classification
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import LeakyReLU
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.models import load_model


In [ ]:
X_train = X_train.astype('float32') / 255.
X_test = X_test.astype('float32') / 255.



# scale data
t = MinMaxScaler()
t.fit(X_train)
X_train = t.transform(X_train)
X_test = t.transform(X_test)

# AutoEncoder Model Preparation
n_inputs = X_train.shape[1]
# define encoder
input_data_shape= Input(shape=(n_inputs,))
# encoder level 1
encoder= Dense(n_inputs*2)(input_data_shape)
encoder = BatchNormalization()(encoder)
encoder= LeakyReLU()(encoder)
# encoder level 2
encoder= Dense(n_inputs)(encoder)
encoder= BatchNormalization()(encoder)
encoder= LeakyReLU()(encoder)
# bottleneck
n_bottleneck = round(float(n_inputs) / 2.0)
bottleneck = Dense(n_bottleneck)(encoder)
# define decoder, level 1
decoder = Dense(n_inputs)(bottleneck)
decoder = BatchNormalization()(decoder)
decoder = LeakyReLU()(decoder)
# decoder level 2
decoder = Dense(n_inputs*2)(decoder)
decoder = BatchNormalization()(decoder)
decoder = LeakyReLU()(decoder)


In [ ]:
# output layer
output = Dense(n_inputs, activation='linear')(decoder)
# define autoencoder model
model = Model(inputs=input_data_shape, outputs=output)
# compile autoencoder model
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
# fit the autoencoder model to reconstruct input
history = model.fit(X_train, X_train,shuffle=True, epochs=5, batch_size=20, validation_data=(X_test, X_test))


Epoch 1/5
36490/36490 [==============================] - 173s 5ms/step - loss: 39.3170 - accuracy: 0.0930 - val_loss: 1784751616.0000 - val_accuracy: 0.0000e+00
Epoch 2/5
36490/36490 [==============================] - 182s 5ms/step - loss: nan - accuracy: 0.0092 - val_loss: nan - val_accuracy: 0.0269
Epoch 3/5
36490/36490 [==============================] - 169s 5ms/step - loss: nan - accuracy: 3.0831e-04 - val_loss: nan - val_accuracy: 0.0269
Epoch 4/5
36490/36490 [==============================] - 179s 5ms/step - loss: nan - accuracy: 3.0831e-04 - val_loss: nan - val_accuracy: 0.0269
Epoch 5/5
36490/36490 [==============================] - 189s 5ms/step - loss: nan - accuracy: 3.0831e-04 - val_loss: nan - val_accuracy: 0.0269


In [ ]:
#Using Logistic Regression Algorithm to the Training Set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression(random_state=0)

In [ ]:
# Returns a NumPy Array
# Predict for One Observation (image)
classifier.predict(X_test[0].reshape(1,-1))

array([2])

In [ ]:
X_test.shape

(312768, 78)

In [ ]:
classifier.predict(X_test[0:10])

array([2, 1, 2, 3, 0, 0, 2, 3, 1, 1])

In [ ]:
predictions = classifier.predict(X_test)

In [ ]:
# Use score method to get accuracy of model
score = classifier.score(X_test, y_test)
print(score)

0.5053522099447514
